export { InventoryStatsCards } from './InventoryStatsCards';
export { InventoryItemFormDialog, type InventoryItemFormData } from './InventoryItemFormDialog';
export { StockMovementDialog, type StockMovementFormData } from './StockMovementDialog';
export { CategoryFormDialog, type CategoryFormData } from './CategoryFormDialog';
export { InventoryTable } from './InventoryTable';
export { MovementsTable } from './MovementsTable';
export { DeleteItemDialog } from './DeleteItemDialog';
export { DeleteCategoryDialog } from './DeleteCategoryDialog';
export { CategoryManagementDialog } from './CategoryManagementDialog';
export { DuplicateItemDialog } from './DuplicateItemDialog';
